### ISSUE TITLE
QA_Recursion_Feature-Links

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#165] opened 2016-02-17 10:04 UTC
Defect Description:
When we click on the Theory link, the feedback link is disappearing in the page instead it should displayed on the screen.

Actual Result:
When we click on the Theory link, the feedback link is disappearing in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Recursion/Recursion_04_Theory_smk.org

![exp6-1](https://cloud.githubusercontent.com/assets/14869397/13105991/e9966aa4-d58b-11e5-91b2-f9bbd07eb169.png)

![exp6-2](https://cloud.githubusercontent.com/assets/14869397/13105997/f0956b3e-d58b-11e5-932f-cd4dd23f2441.png)

**Comment by BSravanthi** [comment] 2016-07-01 09:21
The issue is resolved.

**Comment by BSravanthi** [comment] 2016-07-15 11:00
Issue is fixed now.

**Comment by sadhanareddy** [comment] 2016-07-15 11:03
Issue is fixed. Hence closing the issue.

**Closed by sadhanareddy** 2016-07-15 11:03 UTC
Labels: Category :Functionality, Developed by:IIIT Hyd, Severity :S1, Status :Closed, Version Number : v1.2.0
