### ISSUE TITLE
QA_Factorials_Feature-Links

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#157] opened 2016-02-17 09:42 UTC
Defect Description:
When we click on the Manual link, the feedback link is disappearing in the page instead it should displayed on the screen.

Actual Result:
When we click on the Manual link, the feedback link is disappearing in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Factorials/Factorials_17_Manual_smk.org

![exp4-1](https://cloud.githubusercontent.com/assets/14869397/13105402/0216af56-d589-11e5-86d2-33447fa2d01a.png)
![exp4-2](https://cloud.githubusercontent.com/assets/14869397/13105404/05941e2a-d589-11e5-903b-4746c7757a2c.png)

**Comment by BSravanthi** [comment] 2016-07-01 09:24
The issue is fixed now.

**Comment by sadhanareddy** [comment] 2016-07-15 11:03
Issue is fixed. Hence closing the issue.

**Closed by sadhanareddy** 2016-07-15 11:03 UTC
Labels: Category :Functionality, Developed by:IIIT Hyd, Severity :S1, Status :Closed, Version Number : v1.2.0
