### ISSUE TITLE
QA_Searching and Sorting_Feature-Links

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#174] opened 2016-02-18 04:11 UTC
Defect Description:
When we click on the Theory link, the feedback link is disappearing in the page instead it should displayed on the screen.

Actual Result:
When we click on the Theory link, the feedback link is disappearing in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Searching%20and%20Sorting/Searching%20and%20Sorting_04_Theory_smk.org

![exp8-1](https://cloud.githubusercontent.com/assets/14869397/13133690/b8f81864-d623-11e5-862e-750582304bda.png)
![exp8-2](https://cloud.githubusercontent.com/assets/14869397/13133693/bdc17534-d623-11e5-925b-ceac750c67d2.png)

**Comment by BSravanthi** [comment] 2016-07-01 09:17
Now the issue is resolved.

**Comment by BSravanthi** [comment] 2016-07-15 10:58
Issue is fixed now.

**Comment by sadhanareddy** [comment] 2016-07-15 11:01
Issue is fixed. Hence closing the issue.

**Closed by sadhanareddy** 2016-07-15 11:01 UTC
Labels: Category :Functionality, Developed by:IIIT Hyd, Severity :S1, Status :Closed, Version Number : v1.2.0
