### ISSUE TITLE
QA_Sequences_Feature-Links

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#182] opened 2016-02-18 04:35 UTC
Defect Description:
When we click on the Theory link, the feedback link is disappearing in the page instead it should displayed on the screen.

Actual Result:
When we click on the Theory link, the feedback link is disappearing in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link: 
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Sequences/Sequences_04_Theory_smk.org

![exp10-1](https://cloud.githubusercontent.com/assets/14869397/13133960/f08ded32-d626-11e5-88d2-6efd007a84cd.png)

![exp10-2](https://cloud.githubusercontent.com/assets/14869397/13133962/f8cef180-d626-11e5-8dd3-dee1ff7ec238.png)

**Comment by lalitsanagavarapu** [comment] 2016-03-01 06:25
Feature list consistency bug will be differed. We will take it up as we start working on redesign the labs

**Comment by BSravanthi** [comment] 2016-07-01 07:59
The issue is fixed now.

**Comment by BSravanthi** [comment] 2016-07-15 10:57
Issue is fixed now.

**Comment by sadhanareddy** [comment] 2016-07-15 11:01
Issue is fixed. Hence closing the issue.

**Closed** 2016-07-15 11:01 UTC
Labels: Category :Functionality, Developed by:IIIT Hyd, Severity :S1, Status :Closed, Version Number : v1.2.0
