### ISSUE TITLE
QA_Advanced Arithmatic_Feature-Links

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/problem-solving-iiith#169] opened 2016-02-17 10:16 UTC
Defect Description:
When we click on the Theory link, the feedback link is disappearing in the page instead it should displayed on the screen.

Actual Result:
When we click on the Theory link, the feedback link is disappearing in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/Virtual-Labs/problem-solving-iiith/blob/master/test-cases/integration_test-cases/Advanced%20Arithmatic/Advanced%20Arithmatic_04_Theory_smk.org

![exp7-1](https://cloud.githubusercontent.com/assets/14869397/13106338/b4c5d204-d58d-11e5-9482-3a44d5424436.png)

![exp7-2](https://cloud.githubusercontent.com/assets/14869397/13106343/bb858fa8-d58d-11e5-95bb-1e54d9477267.png)

**Comment by BSravanthi** [comment] 2016-07-01 09:20
The issue is resolved now.

**Comment by BSravanthi** [comment] 2016-07-15 10:59
Issue is fixed now.

**Comment by sadhanareddy** [comment] 2016-07-15 11:02
Issue is fixed. Hence closing the issue.

**Closed by sadhanareddy** 2016-07-15 11:02 UTC
Labels: Category :Functionality, Developed by:IIIT Hyd, Severity :S1, Status :Closed, Version Number : v1.2.0
